### ISSUE TITLE
A scrollbar?

### ISSUE THREAD

**Issue by ghost** [dbeehler/mortalCombotsScoutingApp#2]
Greetings from FTC team #11472!

We've noticed that on some mobile devices or devices with small screens, the input screen (where we can input data for all 4 teams) overflows. The input screen is cut off and **there is no scroll bar or way to scroll down**. The overflow is hidden so we cannot access some input fields.

This is a problem in collecting complete information and although it doesn't matter much because we will only be using this on our alliance (not the other 2 teams), it still would be a good feature.

I do not have the software (Visual Basic) to change this myself, so I'd like to see scroll-bar soon. 

Thanks!
From the Head Programmer of FTC Team 11472 :)
P.S. Even without scrolling, this is really good 👍 . Keep up the good work!

**Comment by dbeehler** [comment]
Thanks for the kind words!
With the issue, I am now working on inputting a scroll bar. Keep checking back, and make sure to watch the repository for any updates!

**Comment by dbeehler** [comment]
It now should work with the updated scrollbar!
